// Représente une fausse API avant Mongo

const ingredients = [
  {
    name: "Ail",
    slug: "ail",
    category: "légume",
    img: "",
    description: "Petit bulbe parfumé utilisé pour relever de nombreux plats.",
    consumption: [
      "janvier",
      "février",
      "mars",
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
      "décembre",
    ],
    recipe: [
      { slug: "verrines_radis_chevre" },
      { slug: "topinambours_lardons_braises" },
      { slug: "poelee_topinambours_carottes_epicee" },
      { slug: "epaule_agneau_poivrons" },
      { slug: "pates_potiron" },
      { slug: "gratin_potiron_boeuf" },
      { slug: "penne_pleurotes_courgette" },
      { slug: "pleurotes_ail" },
      { slug: "veloute_salsifis" },
      { slug: "salsifis_sautes" },
      { slug: "pommes_de_terre_sautees_ail_persil" },
      { slug: "cotes_blettes_bechamel" },
      { slug: "haricots_verts_carbonara" },
      { slug: "puree_laitue_pdt" },
      { slug: "saute_veau_pois" },
      { slug: "veloute_fenouil" },
      { slug: "gaspacho_betterave" },
      { slug: "blettes_bolognaise" },
      { slug: "blettes_sautes_ail_creme" },
      { slug: "aubergines_farcies" },
      { slug: "asperges_roti_laurent_mariotte" },
      { slug: "veloute_celeri_rave" },
      { slug: "soupe_celeri_courgette" },
      { slug: "celeri_rave_roti_ail" },
      { slug: "celeri_champignons_sautes" },
      { slug: "poisson_papillote_chou_chinois" },
      { slug: "wok_chou_chinois_gingembre" },
      { slug: "chou_fleur_roti_ail" },
      { slug: "pot-au-feu" },
    ],
  },
  {
    name: "Asperge blanche",
    slug: "asperge-blanche",
    category: "légume",
    img: "",
    description:
      "Asperge douce et tendre, parfaite cuite à la vapeur ou grillée.",
    consumption: ["avril", "mai", "juin"],
    recipe: [
      { slug: "risotto_legumes_verts" },
      { slug: "veloute_asperges_vertes_blanches" },
      { slug: "asperges_roti_laurent_mariotte" },
      { slug: "gaspacho_asperges_miso" },
    ],
  },
  {
    name: "Asperge verte",
    slug: "asperge-verte",
    category: "légume",
    img: "",
    description: "Asperge croquante et parfumée, idéale en salade ou sautée.",
    consumption: [
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
      "décembre",
    ],
    recipe: [
      { slug: "risotto_legumes_verts" },
      { slug: "veloute_asperges_vertes_blanches" },
      { slug: "asperges_roti_laurent_mariotte" },
      { slug: "gaspacho_asperges_miso" },
    ],
  },
  {
    name: "Aubergine",
    slug: "aubergine",
    category: "légume",
    img: "",
    description: "Légume violet charnu, parfait pour les gratins ou grillades.",
    consumption: ["août", "septembre", "octobre"],
    recipe: [
      { slug: "epaule_agneau_poivrons" },
      { slug: "aubergines_farcies" },
      { slug: "poelee_dinde_aubergine_tomate" },
      { slug: "moussaka_aubergine_agneau" },
    ],
  },
  {
    name: "Betterave rouge",
    slug: "betterave-rouge",
    category: "légume",
    img: "",
    description:
      "Racine ronde et sucrée, parfaite crue en salade ou cuite en accompagnement.",
    consumption: [
      "janvier",
      "février",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
      "décembre",
    ],
    recipe: [
      { slug: "epaule_agneau_poivrons" },
      { slug: "salade_betterave_quinoa_feta_noix" },
      { slug: "verrine_betterave_concombre" },
      { slug: "gaspacho_betterave" },
    ],
  },
  {
    name: "Blette",
    slug: "blette",
    category: "légume",
    img: "",
    description: "Feuille verte et tige croquante, idéale sautée ou en gratin.",
    consumption: [
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
      "décembre",
    ],
    recipe: [
      { slug: "cotes_blettes_bechamel" },
      { slug: "blettes_bolognaise" },
      { slug: "blettes_sautes_ail_creme" },
      { slug: "tourte_blettes_3_fromages" },
    ],
  },
  {
    name: "Brocoli",
    slug: "brocoli",
    category: "légume",
    img: "",
    description:
      "Légume vert riche en vitamines, idéal cuit à la vapeur ou en salade.",
    consumption: [
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
    ],
    recipe: [
      { slug: "gratin_brocolis_haricots_verts" },
      { slug: "timbale_brocoli" },
      { slug: "tarte_brocoli_camembert" },
      { slug: "veloute_brocolis" },
    ],
  },
  {
    name: "Carotte",
    slug: "carotte",
    category: "légume",
    img: "",
    description: "Racine orange sucrée et croquante, idéale crue ou cuite.",
    consumption: [
      "janvier",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
      "décembre",
    ],
    recipe: [
      { slug: "spaghetti_bolognaise" },
      { slug: "topinambours_lardons_braises" },
      { slug: "poelee_topinambours_carottes_epicee" },
      { slug: "gratin_panais_poireaux_carottes_pommes_de_terre" },
      { slug: "epaule_agneau_poivrons" },
      { slug: "vol_au_vent" },
      { slug: "jardiniere_legumes_laitue" },
      { slug: "saute_veau_pois" },
      { slug: "gratin_carottes_patates_douces" },
      { slug: "soupe_epinards" },
      { slug: "chou_blanc_carottes_oignons" },
      { slug: "potee_chou_chinois" },
      { slug: "wok_chou_chinois_gingembre" },
      { slug: "choux_bruxelles_carottes_poeles" },
      { slug: "choux_bruxelles_tomate" },
      { slug: "chou_milan_braise_carottes" },
      { slug: "pot-au-feu" },
    ],
  },
  {
    name: "Cassis",
    slug: "cassis",
    category: "fruit",
    img: "",
    description:
      "Petite baie noire au goût intense et acidulé, idéale en confiture, sirop ou dessert.",
    consumption: ["juillet", "août"],
    recipe: [
      { slug: "tarte_cassis" },
      { slug: "confiture_cassis_rhubarbe" },
      { slug: "muffins_cassis" },
      { slug: "glace_cassis" },
    ],
  },
  {
    name: "Céléri",
    slug: "celeri",
    category: "légume",
    img: "",
    description:
      "Tige croquante et feuilles aromatiques, parfaite crue en salade ou cuite en soupe.",
    consumption: ["juin", "août", "septembre", "octobre", "novembre"],
    recipe: [
      { slug: "vol_au_vent" },
      { slug: "pomme_de_terre_celeri" },
      { slug: "salade_celeri_pomme_noix_fromage" },
      { slug: "soupe_celeri_courgette" },
      { slug: "celeri_champignons_sautes" },
      { slug: "soupe_chou_chinois" },
      { slug: "wok_chou_chinois_gingembre" },
      { slug: "pot-au-feu" },
    ],
  },
];

const recipes = [
  {
    slug: "asperges_roti_laurent_mariotte",
    name: "Asperges blanches et vertes rôties",
    category: "entrée",
    description:
      "Asperges rôties au four avec une sauce à base d'œuf, moutarde, parmesan et huile de pépins de raisin.",
    prix: "bon marché",
    nbr_de_personnes: 1,
    temps_preparation: 30,
    cuisson: 15,
    ingredients: [
      { slug: "asperge_verte", quantite_par_personne: 200, unite: "g" },
      {
        slug: "asperge_blanche",
        quantite_par_personne: 200,
        unite: "g",
      },
      { slug: "oeuf", quantite_par_personne: 0.25, unite: "pièce" },
      { slug: "parmesan_rape", quantite_par_personne: 20, unite: "g" },
      { slug: "moutarde", quantite_par_personne: 1, unite: "c.à.s" },
      { slug: "ail", quantite_par_personne: 0.25, unite: "gousse" },
      { slug: "huile_olive", quantite_par_personne: 1, unite: "c.à.s" },
      {
        slug: "huile_pepin_raison",
        quantite_par_personne: 1,
        unite: "c.à.s",
      },
      { slug: "cerfeuil", quantite_par_personne: 1, unite: "pincée" },
      { slug: "sel", quantite_par_personne: 1, unite: "pincée" },
      { slug: "poivre", quantite_par_personne: 1, unite: "tour" },
    ],
    preparation: [
      "Étape 1: Préchauffer le four à 170°C.",
      "Étape 2: Laver les asperges. Éplucher les asperges blanches à moitié et couper la base. Retirer les picots des asperges vertes et couper la base. Disposer sur une plaque de four recouverte de papier cuisson, arroser d’huile d’olive, saler et poivrer.",
      "Étape 3: Enfourner pour 15 minutes.",
      "Étape 4: Cuire l'œuf dans une casserole d’eau bouillante salée pendant 6 minutes, refroidir et écaler.",
      "Étape 5: Dans un verre mesureur, mixer l'œuf cuit avec la moutarde, l’ail râpé, le parmesan, monter la sauce à l’huile de pépins de raisin. Saler et poivrer.",
      "Étape 6: Vérifier la cuisson des asperges, les disposer dans un plat et napper de sauce. Décorer avec des copeaux de parmesan et du cerfeuil.",
    ],
  },
  {
    slug: "aubergines_farcies",
    name: "Aubergines farcies",
    category: "plat",
    description:
      "Demi-aubergines garnies de légumes ou de viande, relevées d'herbes fraîches et gratinées au four.",
    prix: "bon marché",
    nbr_de_personnes: 1,
    temps_preparation: 15,
    cuisson: 40,
    ingredients: [
      { slug: "aubergine", quantite_par_personne: 0.5, unite: "pièce" },
      { slug: "oignon", quantite_par_personne: 0.5, unite: "pièce" },
      { slug: "tomate", quantite_par_personne: 0.25, unite: "pièce" },
      { slug: "gruyere_rape", quantite_par_personne: 10, unite: "g" },
      { slug: "oeuf", quantite_par_personne: 0.25, unite: "unité" },
      { slug: "chair_saucisse", quantite_par_personne: 25, unite: "g" },
      {
        slug: "huile_olive",
        quantite_par_personne: 1,
        unite: "cuillère à café",
      },
      { slug: "ail", quantite_par_personne: 0.25, unite: "gousse" },
      {
        slug: "persil",
        quantite_par_personne: 1,
        unite: "cuillère à café",
      },
      {
        slug: "basilic",
        quantite_par_personne: 1,
        unite: "cuillère à café",
      },
      { slug: "sel", quantite_par_personne: 1, unite: "pincée" },
      { slug: "poivre", quantite_par_personne: 1, unite: "tour" },
    ],
    preparation: [
      "Étape 1: Couper l'aubergine en deux dans la longueur et inciser la chair en 'X'.",
      "Étape 2: Arroser d'huile d'olive et enfourner à 250°C pendant 30 minutes.",
      "Étape 3: Retirer la chair et la couper finement.",
      "Étape 4: Faire blanchir les oignons à feu doux 15 min, ajouter la chair à saucisse si désiré.",
      "Étape 5: Ajouter les tomates en dés et l'ail, cuire à feu très doux.",
      "Étape 6: Incorporer la chair d'aubergine, le persil, le basilic et l'œuf battu.",
      "Étape 7: Mélanger et remplir les demi-aubergines, saupoudrer de gruyère râpé.",
      "Étape 8: Remettre au four 5-10 minutes dans le four chaud.",
      "Étape 9: Laisser tiédir et servir chaud ou froid.",
    ],
  },
  {
    slug: "blanc_poulet_endives_champignons_lardons",
    name: "Blanc de poulet aux endives, champignons et lardons",
    category: "plat",
    description:
      "Blanc de poulet sauté avec endives, champignons et lardons, parfumé au cognac et à la crème fraîche.",
    prix: "bon marché",
    nbr_de_personnes: 1,
    temps_preparation: 15,
    cuisson: 40,
    ingredients: [
      {
        slug: "blanc_de_poulet",
        quantite_par_personne: 1,
        unite: "pièce",
      },
      {
        slug: "farine",
        quantite_par_personne: 0.25,
        unite: "c. à soupe",
      },
      { slug: "beurre", quantite_par_personne: 0.5, unite: "noix" },
      {
        slug: "lardons_fumes",
        quantite_par_personne: 31.25,
        unite: "g",
      },
      { slug: "oignon", quantite_par_personne: 0.25, unite: "pièce" },
      { slug: "endive", quantite_par_personne: 0.25, unite: "pièce" },
      {
        slug: "champignon_de_paris",
        quantite_par_personne: 50,
        unite: "g",
      },
      {
        slug: "cognac",
        quantite_par_personne: 0.25,
        unite: "c. à soupe",
      },
      {
        slug: "creme_fraiche",
        quantite_par_personne: 1,
        unite: "c. à soupe",
      },
      {
        slug: "persil",
        quantite_par_personne: 0.25,
        unite: "c. à soupe",
      },
      { slug: "sel", quantite_par_personne: 1, unite: "pincée" },
      { slug: "poivre", quantite_par_personne: 1, unite: "tour" },
    ],
    preparation: [
      "Étape 1: Couper le blanc de poulet en petites lamelles et les fariner.",
      "Étape 2: Faire fondre une demi-noix de beurre dans une poêle et y faire revenir les lamelles de poulet jusqu'à ce qu'elles soient dorées. Saler, poivrer et ajouter le cognac. Réserver.",
      "Étape 3: Faire revenir les lardons avec l'autre demi-noix de beurre, ajouter l'oignon émincé et l'endive coupée en petits morceaux. Laisser mijoter environ 5 minutes.",
      "Étape 4: Ajouter les champignons et laisser mijoter encore 5 minutes.",
      "Étape 5: Ajouter le poulet, couvrir et laisser mijoter 20 minutes. Au bout de 15 minutes, incorporer la crème fraîche.",
      "Étape 6: Parsemer de persil juste avant de servir.",
    ],
  },
  {
    slug: "blettes_bolognaise",
    name: "Blettes à la bolognaise",
    category: "plat",
    description:
      "Blettes sautées et mijotées dans une sauce bolognaise maison riche en tomates et aromates.",
    prix: "bon marché",
    nbr_de_personnes: 1,
    temps_preparation: 30,
    cuisson: 25,
    ingredients: [
      { slug: "blette", quantite_par_personne: 150, unite: "g" },
      { slug: "viande_hachee", quantite_par_personne: 100, unite: "g" },
      { slug: "tomate", quantite_par_personne: 1, unite: "unité" },
      { slug: "oignon", quantite_par_personne: 0.5, unite: "unité" },
      { slug: "ail", quantite_par_personne: 0.5, unite: "gousse" },
      {
        slug: "huile_olive",
        quantite_par_personne: 1,
        unite: "cuillère à soupe",
      },
      {
        slug: "bouillon_boeuf",
        quantite_par_personne: 50,
        unite: "ml",
      },
      {
        slug: "persil",
        quantite_par_personne: 1,
        unite: "cuillère à café",
      },
      { slug: "sel", quantite_par_personne: 1, unite: "pincée" },
      { slug: "poivre", quantite_par_personne: 1, unite: "tour" },
    ],
    preparation: [
      "Étape 1: Nettoyez les blettes, retirez la majorité des feuilles et coupez les côtes en tronçons de 2 cm.",
      "Étape 2: Blanchissez les tronçons dans l'eau bouillante pendant 10 minutes.",
      "Étape 3: Émincez l'oignon et l'ail. Pelez, épépinez et découpez les tomates. Hachez le persil.",
      "Étape 4: Faites revenir l'oignon et l'ail dans l'huile d'olive, ajoutez la viande hachée et colorez-la.",
      "Étape 5: Incorporez les tomates, le bouillon, le persil, le sel et le poivre. Laissez mijoter 20 minutes.",
      "Étape 6: Ajoutez les blettes dans la sauce, baissez le feu et laissez cuire doucement 5 à 10 minutes.",
      "Étape 7: Servez chaud.",
    ],
  },
];

module.exports = { ingredients, recipes };
